service: notes-api
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  authorizer:
    handler: authorized.handler
    environment:
      COGNITO_USERPOOL_ID: !Ref cognitoUserPool
      COGNITO_WEB_CLIENT_ID: !Ref cognitoUserPoolWebclient

plugins:
  - serverless-iam-roles-per-function

resources:
  Resources: ${file(resources.yml)}
  
